spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customer
  profiles:
    active: production
  datasource:
    url: ${customer.datasource.url}
    username: ${customer.datasource.username}
    password: ${customer.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver     # org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${customer.datasource.ddl-mode}
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
      exposure:
        include: '*'
info:
  app:
    name: "Customers"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
eureka:
  client: ${eureka-client}
feign:
  hystrix:
    enabled: true
application:
  allow-get-customer: ${customer.allow-get-customer}
server:
  port: 9998
#  port: 8083
#accounts:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:9999,localhost:9998