spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customer
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # ${customer.datasource.ddl-mode}
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
      exposure:
        include: '*'
info:
  app:
    name: "Customers"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}
#eureka:
#  client: ${eureka-client}
feign:
  hystrix:
    enabled: true
application:
  allow-get-customer: true # ${customer.allow-get-customer}
server:
  port: 9998
#  port: 8083
accounts:
#  ribbon:
    eureka:
      enabled: false
#    listOfServers: localhost:9999,localhost:9998